config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #rota padrÃO
  root 'articles#index'  
    
  resources :articles do
    resources :comments, only: %i[create destroy]
  end

  resources :categories, except: [:show]
  #criar rota manual
  #get '/articles', to: 'articles#index'
  #get '/articles/:id', to: 'articles#show'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :category
    belongs_to :user

    has_many :comments, dependent: :destroy

    validates :title, presence: true,length: {minimum:3, maximum:20} 
    validates :body, presence: true, length: {minimum:5}
    
    paginates_per 2

    scope :desc_order, -> { order(created_at: :desc) }
    scope :without_highlights, ->(ids) { where("id NOT IN (#{ids})") if ids.present? }
    scope :filter_by_category, ->(category) { where category_id: category.id  if category.present? }
    
    scope :filter_by_archive, lambda { |month_year|
        if month_year
            date = Date.strptime(month_year, '%B %Y')
            where created_at: date.beginning_of_month..date.end_of_month.next_day
        end        
    }
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error
    
    validates :name, presence: true,
    length: {minimum:3},
    uniqueness: { case_sensitive: false }

    scope :sorted, -> { order(:name) }
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  devise :confirmable, 
         :database_authenticatable, 
         :recoverable, 
         :registerable,         
         :rememberable, 
         :trackable,
         :validatable
                                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Paginable

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[edit update destroy]
  before_action :set_categories, only: %i[new create edit update]

  def index
    @categories = Category.sorted

    #evidante selects desnecesários 
    category =  @categories.select { |c| c.name == params[:category] }[0] if params[:category].present?

    @highlights = Article.includes(:category, :user)
                         .filter_by_category(category)
                         .filter_by_archive(params[:month_year])
                         .desc_order
                         .first(3)
    
    #incluído no concerns
    #current_page = (params[:page] || 1).to_i 
    highlight_ids = @highlights.pluck(:id).join(',')

    

    @articles = Article.includes(:category, :user )
                       .without_highlights(highlight_ids)
                       .filter_by_category(category)
                       .filter_by_archive(params[:month_year])
                       .desc_order                       
                       .page(current_page)

    @archives = Article.group_by_month(:created_at, format: '%B %Y').count

    
    
                 
    # @articles = Article.order(created_at: :desc)
   #                    .where('id NOT IN (?)',highlight_ids)
   #                    .page(current_page).per(2)
  #tewste    
  end

  def show
    @article = Article.includes(comments: :user).find(params[:id])
    authorize @article
  end 
 
  def new
    @article = current_user.articles.new 
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new
    end
  end

  def edit 
    
  end 

  def update
    
    
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit
    end 
  end 

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, notice: "Article was successfully destroyed."
  end   

  private 
  def article_params
    params.require(:article).permit(:title, :body, :category_id)
  end 

  def set_article
    @article = Article.find(params[:id])
    authorize @article
    
  end  

  def set_categories
    @categories = Category.sorted
  end  
  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = policy_scope(Category.sorted)
    #policy_scope aplicar política do pundit quando retorna vários registros
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
    
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy    
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
        format.json { head :no_content }
      end
    else 
      redirect_to categories_url, alert: @category.errors.messages[:base][0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      authorize @category
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_article

    def create
        @article.comments.create(comment_params.to_h.merge!({ user_id: current_user.id }))
        redirect_to article_path(@article), notice: 'Comment was successfully created.'
    end     

    def destroy
        comment = @article.comments.find(params[:id])
        authorize comment

        comment.destroy
        redirect_to article_path(@article), notice: 'Comment was successfully destroyed.'
    end     
    
    
    private 

    def comment_params
        params.require(:comment).permit(:body)
    end    

    def set_article
        @article = Article.find(params[:article_id])
    end
      
end 

app/controllers/concerns/paginable.rb
module Paginable
    protected

    def current_page
        (params[:page] || 1).to_i 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def month_day_comma_year(datetime)
        datetime.strftime('%B %e, %y')        
    end 
    
    def render_if(condition, template, record)
        render template, record if condition
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comemnts_helper.rb
module ComemntsHelper
end

app/views/articles/_about.html.erb
        <div class="p-4 mb-3 bg-light rounded">
          <h4 class="fst-italic">About</h4>
          <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
        </div>

app/views/articles/_archives.html.erb
<div class="p-4">
    <h4 class="fst-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
        <% @archives.each do |month_year, count| %>
        <li>
            <%= link_to "#{month_year} (#{count}) ", articles_path(month_year: month_year),
                class: "p-2 link-secondary #{'filter-active' if month_year == params[:month_year] } "  %>
        </li>
        <% end %>         
        
   
    </ol>
</div>

app/views/articles/_article.html.erb
<article class="blog-post">
        <h2 class="blog-post-title"> <%= article.title %> </h2>
        <p class="blog-post-meta"> 
        <%= render 'article_detail', article: article %>
        
        </p>

        <p> <%= truncate(article.body, length: 150 ) %> </p>

        <p> <%= link_to 'Continue reading...', article, class: 'btn btn-link' %> </p> 

        <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary' if policy(article).update? %> 
        <%= link_to 'Destroy', article_path(article), 
        method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' if policy(article).destroy? %> 

</article>

app/views/articles/_article_detail.html.erb
<%= month_day_comma_year(article.created_at) %> by 
<%= article.user.email %> in 
<%= article.category.name %> 

app/views/articles/_elsewhere.html.erb
        <div class="p-4">
          <h4 class="fst-italic">Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a href="https://github.com/glaylson" target= "_blank" >GitHub</a></li>
            <li><a href="https://www.linkedin.com/in/glaylson-alves-69382278/" target= "_blank" >Linkedin</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
        </div>
      
      

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
    <div class="form-inputs"> 
        <%= f.input :title %>
        <%= f.input :body, input_html: { rows: 10 } %>
        <%= f.association :category, collection:  @categories, prompt: "Chose a Category" %>
    </div>

    <div class="form-action"> 
        <%= f.button :submit, class: 'btn btn-primary' %>        
        <%= link_to 'Back', article, class: 'btn btn-secondary' %> 
    </div>

<%end%> 

app/views/articles/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic"> <%= article.title %> </h1>
        <p class="lead my-3">  <%= truncate(article.body, lengh: 100) %> </p>
        <p class="lead mb-0">
            <%= link_to 'Continure reading...',article,class: 'text-whith fw-bold'%>
        </p>
    </div>
</div>

app/views/articles/_medium_featured.html.erb
<div class="col-md-6">
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary">
      <%= article.category.name %>
      </strong>
      
      <h3 class="mb-0"><%= article.title %></h3>
      <div class="mb-1 text-muted"> 
        <%= render 'article_detail', article: article %>
      </div>
      <p class="card-text mb-auto">
        <%= truncate(article.body, lengh: 100) %>
      </p>
  
      <%= link_to 'Continure reading...',article,class: 'stretched-link'%>

    </div>
    <div class="col-auto d-none d-lg-block">
      <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

    </div>
  </div>
</div>

app/views/articles/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">
    
    <%= link_to_next_page @articles, 'Older', class: 'btn btn-outline-primary' %> 
    <%= link_to_previous_page @articles, 'Newer', class: 'btn btn-outline-primary' %> 
            
</nav>

app/views/articles/_right_side.html.erb
<div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
        <%= render 'about' %>

        <%= render 'archives' %>

        <%= render 'elsewhere' %>

    </div>
</div>    

app/views/articles/edit.html.erb
<h1> Update Article </h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<%= render_if @highlights[0].present?, 'longer_featured', article: @highlights[0] %>

<div class="row mb-2">
    <%= render_if @highlights[1].present?, 'medium_featured',article: @highlights[1] %>
    <%= render_if @highlights[2].present?, 'medium_featured',article: @highlights[2] %>
</div>

  <div class="row g-5">
    <div class="col-md-8">
        <h3 class="pb-4 mb-4 fst-italic border-bottom">
            From my experience
        </h3>

        <p>
        <%= link_to 'New Article', new_article_path, class: 'btn btn-success' if user_signed_in? %>
        </p>

        
        <%= render  @articles %>
        
        <%= render 'pagination' %>

      </div>

      <%= render 'right_side' %>
</div>   

<%= content_for :category_filter  do %>
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <% @categories.each do |category| %>
          <%# enviar parametro para ser filtrado  %>
          <%= link_to category.name, articles_path(category: category.name),
            class: "p-2 link-secondary #{'filter-active' if category.name.to_s == params[:category] } "  %>
          <% end %>

        </nav>
      </div>
<% end %>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<article class="blog-post">
        <h2 class="blog-post-title"> <%= @article.title %> </h2>
        <p class="blog-post-meta"> 
        <%= render 'article_detail', article: @article %>

        </p>

        
                        
        <p> <%= @article.body %> </p>
        

        <%= link_to 'Edit', edit_article_path(@article), 
        class: 'btn btn-primary' if policy(@article).update?
        %> 
        <%= link_to 'Destroy', article_path(@article), 
        method: :delete,
        data: { confirm: 'Are you sure?' }, 
        class: 'btn btn-danger' if policy(@article).destroy?
        
        %> 

         <%= link_to 'Back', root_path , class: 'btn btn-secondary' %> 

        <h2 class= "mt-3">Comments</h2>

        <%= render @article.comments %>      
        <%# outra forma g
        <%# <% @article.comments.each do |comment| %>
        <%#        <div class="card mb-3">
        <%#        <div class="card-body">
        <%#                <h5 class="card-title"><%= month_day_comma_year(comment.created_at) %></h5>
        <%#                <h6 class="card-subtitle mb-2 text-muted">Commenter: <%= comment.user.email %> </h6>
        <%#                <p class="card-text"> <%= comment.body %> </p>                        
        <%#        </div>
        <%#        </div>
        <%# <% end %>

        <h2>Add a comment:</h2>
        <% if policy(:comment).create? %>        
           <%= render 'comments/form' %>
        <% else %>
        Please, login to create a comment.
        <% end %>

</article>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,class: 'btn btn-primary' %>
  </div>
<% end %>

  

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<p>
  <%= link_to 'New Category', new_category_path, 
  class: 'btn btn-primary' if policy(:category).new? %>
</p>

<table class= "table table-striped table-hover table-bordered ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
          <td>            
            <%= link_to 'Edit', edit_category_path(category) if policy(category).udpate? %>
            <%= link_to 'Destroy', category, 
            method: :delete, data: { confirm: 'Are you sure?' } if policy(category).destroy? %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<div class="card mb-3">
<div class="card-body">
        <h5 class="card-title"><%= month_day_comma_year(comment.created_at) %></h5>
        <h6 class="card-subtitle mb-2 text-muted">Commenter: <%= comment.user.email %> </h6>
        <p class="card-text"> <%= comment.body %> </p>  

        <%= link_to 'Destroy', article_comment_path(@article, comment), 
        method: :delete,
        data: { confirm: 'Are you sure?' }, 
        class: 'btn btn-danger' if policy(comment).destroy?
        
        %>                      
</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for  [@article, @article.comments.build] do |f| %>
    <div class="form-inputs">                 
            <%= f.input :body, input_html: { rows: 10 } %>                
    </div>

    <div class="form-action"> 
            <%= f.button :submit, class: 'btn btn-primary' %>                        
    </div>

<%end%> 

app/views/layouts/_account_links.html.erb
<% if user_signed_in? %>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.email %>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li>
        <%= link_to 'Edit User', edit_user_registration_path, class: "dropdown-item" %>
    </li>
    <li> <hr class="dropdown-divider"> </li>
    <li>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </li>
  </ul>
</div>
<% else %>
    <%= link_to 'Sign in', new_user_session_path, class: "link-secondary" %>&nbsp;&nbsp;
    <%= link_to 'Sign out', edit_user_registration_path, class: "btn btn-sm btn-outline-secondary" %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>



<% if alert.present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
    <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    <p>
    <a href="#">Back to top</a>
    </p>
</footer>

app/views/layouts/_topnavbar.html.erb
<div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          
          <div class="col-4 pt-1">            
            <%= link_to "Categories", categories_path, class: 'link-secondary' if policy(:category).index?
            %>
          </div>

          <div class="col-4 text-center">            
            <%= link_to "Glaylson Alves's Blog", root_path, class: 'blog-header-logo text-dark' %>          
          </div>

          <div class="col-4 d-flex justify-content-end align-items-center">
            <%= render 'layouts/account_links' %>
          </div>
        </div>
      </header>

      <%= yield :category_filter %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp01</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    

    <%= render 'layouts/topnavbar' %>
    <main class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  

   
  </body>
</html>